# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea21767159873c279bb3db57ad423768cd5ead427346e77bd965cf21474f41e21772f7c9564ccf7130a9eea74f5c5cd8a3c32571b45aaa679f5394b6ec162e6

test:
  secret_key_base: 924a1093ef532118599db505b1694c9913a6e4b699191743a5a5f3699d26ae35f5932dc1a22fb8b657c9bc10e841a0fc0c9d607f4d7515093bb48747bf92dbf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
